name: Publish docker image to Dockerhub

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
    - name: Docker meta
      id:  meta
      uses: docker/metadata-action@v3
      with:
        images: ianhchamberlain/rpmlint
        tags: |
          type=semver,pattern={{version}}
          type=sha
          
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
